### ISSUE TITLE
When "sendMessage('fail.timeout');" throws an exception the phantom process will live forever!

### ISSUE THREAD

**Issue by aetheon** [gruntjs/grunt-lib-phantomjs#29]
Hi,

I'm using "grunt-contrib-jasmine" and the panthom.js process keeps growing on the system.

After a little debug I found that "grunt-contrib-jasmine" is calling halt() method witch unlink the tmp file used for sendMessage. After this the "fail.timeout" method is failing  on sendMessage because it cannot write to the file and the "phantom.exit();" never gets called.

To fix it on my machine I surrounded the sendMessage with try/catch on the "fail.timeout" sendMessage.

Let me know if some more info is needed.
Regards.

**Comment by Arkni** [comment]
It's been almost 2 years since you encountered this issue and no comment from you that confirm if the issue still there or you fixed it somehow.

Closing for now , if you still encountering the same error when using the latest version of `grunt-contrib-jasmine`, please report it and we will reopen this issue.
