### ISSUE TITLE
Facing issue while executing mvn clean install 

### ISSUE THREAD

**Issue by ponnuru** [gruntjs/grunt-lib-phantomjs#54]
Testing jasmine specs via phantom

Running PhantomJS...←[31mERROR←[39m
←[31m>> ←[39mTypeError: Cannot call method 'charAt' of null 0 [ 'TypeError: Cannot call method \'charAt\' of null' ]
←[31m>> ←[39mIn order for this task to work properly, PhantomJS must be installed locally←[31m
>> ←[39mvia NPM. If you're seeing this message, generally that means the NPM install←[31m
>> ←[39mhas failed. Please submit an issue providing as much detail as possible at:←[31m
>> ←[39mhttps://github.com/gruntjs/grunt-lib-phantomjs/issues
←[33mWarning: PhantomJS not found. Use --force to continue.←[39m

**Comment by udayas8451** [comment]
When in run jasmine using grunt i see the following message. But this generates specRunner html file.Im trying to get the test execution summary on command line. And it fails because of following message.

Running "jasmine:unit" (jasmine) task
Testing jasmine specs via PhantomJS

Warning: Cannot read property 'pid' of undefined Use --force to continue.

Aborted due to warnings.

Versions:
=======
Phantomjsjs: 1.9.8
grunt-contrib-jasmine: ~0.9(what ever is the latest)

"grunt server --stack" logs:
=====================
TypeError: Cannot read property 'pid' of undefined
    at kill (C:\nodejs\sample\node_modules\grunt-contrib-jasmine\node_modules\grun
t-lib-phantomjs\lib\phantomjs.js:59:28)
    at cleanup (C:\nodejs\sample\node_modules\grunt-contrib-jasmine\node_modules\g
runt-lib-phantomjs\lib\phantomjs.js:65:31)
    at C:\nodejs\sample\node_modules\grunt-contrib-jasmine\node_modules\grunt-lib-
phantomjs\lib\phantomjs.js:174:7
    at callDone (C:\nodejs\sample\node_modules\grunt\node_modules\grunt-legacy-uti
l\index.js:159:5)
    at Object.util.spawn (C:\nodejs\sample\node_modules\grunt\node_modules\grunt-l
egacy-util\index.js:178:7)
    at EventEmitter.exports.spawn (C:\nodejs\sample\node_modules\grunt-contrib-jas
mine\node_modules\grunt-lib-phantomjs\lib\phantomjs.js:164:41)
    at phantomRunner (C:\nodejs\sample\node_modules\grunt-contrib-jasmine\tasks\ja
smine.js:140:15)
    at Object.<anonymous> (C:\nodejs\sample\node_modules\grunt-contrib-jasmine\tas
ks\jasmine.js:108:5)
    at Object.<anonymous> (C:\nodejs\sample\node_modules\grunt\lib\grunt\task.js:2
64:15)
    at Object.thisTask.fn (C:\nodejs\sample\node_modules\grunt\lib\grunt\task.js:8
2:16)

Aborted due to warnings.


Please help me. What am I doing wrong here?

Thanks!

**Comment by Arkni** [comment]
From all the stack traces above, that there is a problem with the path of `PhantomJS` binary. The package [`phantomjs`](https://github.com/Medium/phantomjs) (aka `phantomjs-prebuilt`) is the one responsible for installing and providing us the path of `PhantomJS` binary.
So this issue has nothing to do with this package even if the error message says otherwise.

A fresh install of this package should fix the issue. If persist, please report it to https://github.com/Medium/phantomjs.

Closing this for now, feel free to ask if you have followup questions.
