### ISSUE TITLE
Support SlimerJS

### ISSUE THREAD

**Issue by cburgmer** [gruntjs/grunt-lib-phantomjs#57]
I have a bunch of tests that do not work in PhantomJS due to the very old version of WebKit they are employing. I'd like to have the option of switching to SlimerJS which implements the same API as PhantomJS, but runs JS against an up-to-date Firefox.

What would be a feasible approach to optionally switch to SlimerJS at runtime, assuming that all existing code would work exactly the same? The switch should probably be made transparent for the consumers of the grunt-lib-phantomjs dependency.

A first step could just be finding a good "switch" capability (a global setting in the Gruntfile or else) and making a proof of concept implementation.

Would that be in the scope of this project?

**Comment by Arkni** [comment]
FYI, the latest release of this lib uses `PhantomJS` `v2.1.1` which is the latest release that based on an updated version of `WebKit` (see [here](http://phantomjs.org/release-2.0.html) and [here](http://phantomjs.org/release-2.1.html)).

If we did the switch, this lib should be renamed to something else and need to depend on an installer of `SlimerJS` (if exist). So this issue is out of the scope of this project.
I suggest creating a generic lib that have options to choose whether you want to use `PhantomJS` or `SlimerJS`.

Closing this for now, feel free to ask if you have followup questions.
