### ISSUE TITLE
it is possible to run grunt-lib-phantomjs with phantom 2.0.0?

### ISSUE THREAD

**Issue by cesarpachon** [gruntjs/grunt-lib-phantomjs#94]
hello, I need run jasmine tests against phantom 2.0.0 (due to IndexedDB support). grunt-contrib-jasmine 0.9.2 uses grunt-lib-phantomjs 0.7.1. I manually downloaded, build and replace the binary from: 
.node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs 
to the newly compiled 2.0.0 version, but now when I run the specs it just print the initial message and stay opened, doing nothing: 

Running "jasmine:test" (jasmine) task
Testing jasmine specs via PhantomJS

no errors, so I wonder what could be wrong with this approach.

**Comment by antivanov** [comment]
I had to run grunt-lib-phantomjs with PhanthomJS 2.0 because of memory leak issues in the older version of PhantomJS. 

It seems that at the moment PhantomJS 2.0 is not stable enough and I had some issues with running it in a Linux environment.

If you still want to use PhantomJS 2.0 you can use the following unofficial forks of `grunt-contrib-jasmine-phantomjs` and `grunt-lib-phantomjs` I created:

https://www.npmjs.com/package/grunt-contrib-jasmine-phantomjs2-unofficial
https://www.npmjs.com/package/grunt-lib-phantomjs2-unofficial

**Comment by flozz** [comment]
Hello,

PhantomJS 2.1 was released this week. Is it possible to upgrade? :)

* https://www.npmjs.com/package/phantomjs

**Comment by Arkni** [comment]
@flozz 
se e #96

**Comment by vladikoff** [comment]
merged
